version:  '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports: 
      - "3005:3005"
    volumes:
      - /app/node_modules
      - .:/app
  
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]  
